name: Cineverse
options:
  bundleIdPrefix: com.cineverse
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

targets:
  Cineverse:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Cineverse
        excludes:
          - "*.plist"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cineverse.app
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: Cineverse/Info.plist
      TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: Alamofire
      - package: SDWebImage
      - package: TelemetryDeck
    info:
      path: Cineverse/Info.plist
      properties:
        CFBundleDisplayName: Cineverse
        CFBundleIdentifier: com.cineverse.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
                UISceneStoryboardFile: Main

  CineverseTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: CineverseTests
    dependencies:
      - target: Cineverse
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cineverse.tests
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.10.2
  SDWebImage:
    url: https://github.com/SDWebImage/SDWebImage.git
    from: 5.21.1
  TelemetryDeck:
    url: https://github.com/TelemetryDeck/SwiftSDK
    branch: main

schemes:
  Cineverse:
    build:
      targets:
        Cineverse: all
    test:
      targets:
        - CineverseTests
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release 