name: Cineverse
options:
  bundleIdPrefix: com.cineverse
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  developmentRegion: en

settings:
  SWIFT_VERSION: "5.9"
  CODE_SIGN_STYLE: Automatic

targets:
  Cineverse:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Cineverse
        excludes:
          - "*.plist"
    info:
      path: Cineverse/Info.plist
      properties:
        CFBundleDisplayName: Cineverse
        CFBundleIdentifier: com.cineverse.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cineverse.app
    dependencies:
      - package: Alamofire
      - package: SDWebImage
      - package: TelemetryDeck

  CineverseTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: CineverseTests
    dependencies:
      - target: Cineverse
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cineverse.tests
      GENERATE_INFOPLIST_FILE: YES

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.8.1
  SDWebImage:
    url: https://github.com/SDWebImage/SDWebImage.git
    from: 5.18.10
  TelemetryDeck:
    url: https://github.com/TelemetryDeck/SwiftSDK
    branch: main

schemes:
  Cineverse:
    build:
      targets:
        Cineverse: all
    test:
      targets:
        - CineverseTests
