name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-14
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        xcode: ['16.2']
        simulator: ['platform=iOS Simulator,name=iPhone 16']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Secrets.xcconfig
        run: |
          echo "TMDB_API_KEY = ${{ secrets.TMDB_API_KEY }}" > Secrets.xcconfig

      - name: Verify File Creation and Content
        run: |
          echo "--- Checking directory structure ---"
          ls -R

          echo "--- Checking content of Secrets.xcconfig ---"
          cat Secrets.xcconfig

      - name: Set up Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Build Cineverse
        run: |
          xcodebuild -project Cineverse.xcodeproj -scheme Cineverse \
            -destination '${{ matrix.simulator }}' \
                       build

      - name: Run unit tests
        run: |
          set -o pipefail && \
          xcodebuild test -project Cineverse.xcodeproj -scheme Cineverse \
            -destination '${{ matrix.simulator }}' \
                       -resultBundlePath ./TestResults.xcresult | xcpretty

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults.xcresult
