name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Debug environment
        run: |
          pwd
          ls -la
          echo "Xcode version:"
          xcodebuild -version
          echo "Available simulators:"
          xcrun simctl list devices available | grep iPhone

      - name: Build Cineverse
        run: |
          xcodebuild -project Cineverse.xcodeproj -scheme Cineverse \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            build

      - name: Run unit tests
        run: |
          xcodebuild test -project Cineverse.xcodeproj -scheme Cineverse \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -resultBundlePath ./TestResults.xcresult

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults.xcresult 