name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-14
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        xcode: ['16.0']
        simulator: ['platform=iOS Simulator,name=iPhone 16,OS=17.6']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Build Cineverse
        run: |
          set -o pipefail && \
          xcodebuild -project Cineverse.xcodeproj -scheme Cineverse \
            -destination '${{ matrix.simulator }}' \
            build | xcpretty

      - name: Run unit tests
        run: |
          set -o pipefail && \
          xcodebuild test -project Cineverse.xcodeproj -scheme Cineverse \
            -destination '${{ matrix.simulator }}' \
            -resultBundlePath ./TestResults.xcresult | xcpretty

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults.xcresult

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults.xcresult 